permissions:
  contents: write
  actions: read
  checks: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  statuses: write

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@master

      # Install necessary dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxcursor-dev libxrandr-dev libxi-dev libgl1-mesa-dev xorg-dev xauth xorg xserver-xorg xvfb
          sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev libxcb-icccm4-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-render0-dev libxcb-xkb-dev libxkbcommon-x11-dev
          sudo apt-get install -y build-essential

      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISPLAY: ":0"
        with:
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE"
